development:
  adapter: mysql2
  database: jordana
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: jordana_production
  username: jordana_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: utf8
  pool: 25
  timeout: 5000
